<?php (defined('BASEPATH')) OR exit('No direct script access allowed');

class MY_Config extends CI_Config
{
	function save_config($module, $is_development = FALSE)
	{
		$path = "modules";
		$config_data = $this->config;
		if ($is_development)
		{
			$path = "development";
		}
		require "./application/{$path}/{$module}/config/config.php";
		foreach ($config as $key => $value)
		{
			if (isset($config_data[$key]))
			{
				$config[$key] = $config_data[$key];
			}
		}
		$ci =& get_instance();
		$ci->load->helper("file");
		write_file("./application/{$path}/{$module}/config/config.php", self::_parse_file_data($config));
	}
	
	private function _parse_file_data($data)
	{
		$file = '';
		$is_object = is_object($data);
		
		if ($is_object)
		{
			$data = serialize($data);
		}
		
		$file .= '<?php if ( ! defined("BASEPATH")) exit("No direct script access allowed");';
		$file .= "\n// @note - Do not edit this file directly. It is automatically generated. \n";
	
		if (is_array($data))
		{
			foreach ($data as $key => $value) {
				$file .= '$config' . "['$key'] = '$value';\n";
			}
		}
		else
		{
			$file .= '$config' . "['$var_name'] = ";
		}
			
		// Finalize File Contents and append a semicolon to PHP data
		if (!is_array($data))
		{
			$file .= $is_object ? 'unserialize(': '';
			$file .= var_export($data, TRUE) . ($is_object ? ');': ';');
		}
		return $file;
	} 
}
